export TEXMFOUTPUT=../tmp/
LATEX=pdflatex

praca.pdf: praca.tex bibliografia.tex rozdzial1.tex rozdzial2.tex rozdzial3.tex rozdzial4.tex rozdzial5.tex rozdzial6.tex stronatytulowa.tex wstep.tex
	$(LATEX) -halt-on-error praca.tex
	$(LATEX) -halt-on-error praca.tex
